platforms:
  ios:
    targets:
      App:
        plist:
          - replace: true
            entries:
              - NSBluetoothPeripheralUsageDescription:
                  - Connection to peripherals requires bluetooth control
              - NSBluetoothAlwaysUsageDescription:
                  - Connection to peripherals requires bluetooth control
  android:
    manifest:
      - file: AndroidManifest.xml
        target: manifest
        merge: |
          <manifest>
            <uses-permission android:name="com.google.android.gms.permission.AD_ID"/>
            <uses-permission android:name="android.permission.BLUETOOTH" android:maxSdkVersion="30" />
            <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" android:maxSdkVersion="30" />
            <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
          </manifest>